apiVersion: v1
kind: Service
metadata:
  name: energy-transmission-web
  namespace: energy-transmission
spec:
  type: LoadBalancer
  selector:
    app: energy-transmission-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
