pipeline {
  agent any
  stages {
    stage('Checkout') {
      steps { checkout scm }
    }
    stage('Build image') {
      steps {
        sh 'docker build -t energy-dashboard:ci apps/energy-dashboard'
      }
    }
    stage('Archive') {
      steps {
        archiveArtifacts artifacts: '**/*.yaml', fingerprint: true
      }
    }
  }
}
